### PR TITLE
xtimer: remove return value for usleep_until

### PR DESCRIPTION
**Pull request by OlegHahm**
Just throw it away if you dislike the 8 bytes more of ROM.

### CODE REVIEW

**Comment by kaspar030** [comment]
While the return value is useless, I'm happy with changing the signature.

I don't like dropping the gotos.

While using goto to handle early outs in fuctions is considered best practice in C, having multiple returns per function is the opposite. Also, having a control keyword (goto out) instead of an assignment (*last_wakeup = xtimer_now()) seem a lot more maintainable to me.

Furthermore, explicitly writing out the assignment + function call three times would, with a bad compiler, lead to code duplication. So this doesn't even only look like its wasteful, it also depends on the compiler to sort that out.

**Comment by OlegHahm** [comment]
> While using goto to handle early outs in fuctions is considered best practice in C

That's the first time I hear that. Do you have a reference?

> having multiple returns per function is the opposite

I was told differently: https://github.com/RIOT-OS/RIOT/pull/1228#discussion_r13378157 ;)

But as I wrote, just take what you like, it's not a big change anyway, but I had made these changes locally and put them here instead of just throwing them away directly.

**Comment by kaspar030** [comment]
> > While using goto to handle early outs in fuctions is considered best practice in C
> 
> That's the first time I hear that. Do you have a reference?

Well, best practice might overstate it, but I was referring to linux Documentation/CodingStyle Chapter 7.

**Comment by kaspar030** [comment]
But could you remove the goto-removal and just keep the return value change?

**Comment by OlegHahm** [comment]
done

**Comment by kaspar030** [comment]
nice, thanks!

**Comment by OlegHahm** [comment]
btw. actually I found a reference: "Dennis Ritchie and Brian Kernighan warn that goto is "infinitely abusable", but also suggest that it could be used for end-of-function error handlers and for multi-level breaks from loops."

**Pull request merged**
